examples/js/avatar-body.component.js
examples/super/process/vxr-host-template.html
examples/super/process/vxr-spectator-template.html

Created avatar body component and modified vxr host and spectator template

Avatar Body Component 

---

examples/Laboratory.html
examples/Models/gltf/Scene_Base.gltf
examples/Models/gltf/Scene_Base02.gltf
examples/Models/gltf/Scene_Ieproesblogo.gltf
examples/Models/gltf/Scene_Medixlablogo.glb
examples/Models/gltf/Scene_Medixlablogo.gltf
examples/Models/gltf/Scene_Row.gltf
examples/Models/gltf/Scene_VertexLogo.gltf
examples/basic-5.html

Added the edited meshes on gltf on laboratorie html file and added new environment component

Added new environment component and added new gltf files on aframe

---

examples/auditorio.html

Set spawn positions for avatars.

spawn_positions

---

examples/Models/gltf/AllisTweezers.gltf
examples/Models/gltf/ButtonedScissors.gltf
examples/Models/gltf/GlovesClean.gltf
examples/Models/gltf/GlovesPaper.gltf
examples/Models/gltf/Rubber.gltf
examples/Models/gltf/SpectatorAvatarBody.gltf
examples/Models/gltf/SpectatorAvatarHead.gltf
examples/Models/gltf/TeacherAvatarBody.gltf
examples/Models/gltf/TeacherAvatarHead.gltf

Added the gltf files of those on glb and made modification on mesh avatar for teacher and spectator

Made changes on assets models and added new models

---

examples/super/process/vxr-spectator-template.html

Modified the environment and lights with new changes and set 11 spawn points

set environment and spawn points

---

examples/super/process/vxr-spectator-template.html

set new spawn point

---

examples/super/process/vxr-student-template.html
examples/super/process/vxr-teacher-template.html

Added spawn positions, new assets and lights to the scenery

added new assets and lights

---

examples/Laboratory.html
examples/Models/gltf/Bed.gltf
examples/Models/gltf/Scene_Lamps1.gltf
examples/Models/gltf/Scene_Row.gltf

Made changes on scenery meshes and laboratory and changed a file for gltf with a low poly

Changed scenery meshes and updated an asset with a less size 

---

examples/super/process/vxr-spectator-template.html
examples/super/process/vxr-student-template.html
examples/super/process/vxr-teacher-template.html

Removed physics from spectator objects.

Changes on Spectator objects template

---

examples/Models/gltf/Columns_Auditorium.gltf
examples/Models/gltf/Roof_Auditorium.gltf

Modified the meshes for auditorium and updated the gltf files

Made changes on stairs, spectator avatar, roof and columns on auditorium

---

examples/super/process/vxr-student-template.html
examples/super/process/vxr-teacher-template.html

Erased unused lights and shadows for teacher and student template

Made changes on teacher and student template

---

examples/js/set-name.component.js
examples/super/process/vxr-spectator-template.html

modified positions for spawn points on the scenery

spawn points

---

examples/super/process/vxr-spectator-template.html
examples/super/process/vxr-student-template.html
examples/super/process/vxr-teacher-template.html

Changed screen curve to a plane and update spawn points on teacher and student files

screen curve and spawn points

---

examples/Models/gltf/CottonSwabs01.gltf
examples/Models/gltf/CottonSwabs02.gltf
examples/Models/gltf/CottonSwabs03.gltf
examples/Models/gltf/Gauze.gltf
examples/Models/gltf/HeparinSeal.gltf
examples/Models/gltf/Intracath.gltf
examples/super/process/vxr-teacher-template-test.html

Added assets with less size and made a copy for teacher template and added assets with dynamic

Made changes on assets size and added dynamic entitys on teacher template

---

examples/super/process/vxr-teacher-template-test.html
examples/super/process/vxr-teacher-template.html

Made the corresponded changes on teacher template that were made on teacher template test

Added assest for dynamics on teacher template and update

---

examples/IEPROES/Process-Assist-NeoNato/vxr-spectator-template.html
examples/IEPROES/Process-Assist-NeoNato/vxr-teacher-template.html

lights for nenonato process updated

Modified lights

---

examples/IEPROES/Process-Assist-NeoNato/vxr-spectator-template.html
examples/IEPROES/Process-Assist-NeoNato/vxr-teacher-template.html
examples/super/process/assets/avatars/SpectatorAvatarBody.gltf
examples/super/process/assets/avatars/SpectatorAvatarHead.gltf

Fix double body

---

examples/vxr-spectator-scenery.html
examples/vxr-student-scenery.html
examples/vxr-teacher-scenery.html

Create new spectator, student and teacher experiences files

vxr-templates scenery

---

examples/Models/Images/sky-01.jpg
examples/Models/gltf/BedHospital.gltf
examples/Models/gltf/CubeBone.gltf
examples/Models/gltf/HospitalRoom.gltf
examples/Models/gltf/Patient_Static.gltf
examples/Models/gltf/cubeik.gltf
examples/js/feature-set-position.component.js
examples/super/process/vxr-spectator-template.html
examples/super/process/vxr-teacher-template.html

Added Sky to main map

---

examples/IEPROES/Process6/vxr-teacher-template.html
examples/js/structureEntitiesProcess6.json

Added Hospital Room and modified illumination

---

examples/IEPROES/Process1/Assets/level1/Covid_Boot_L.gltf
examples/IEPROES/Process1/Assets/level1/Covid_Boot_R.gltf
examples/IEPROES/Process1/Assets/level1/Escafandra_Low.gltf
examples/IEPROES/Process1/Assets/level1/Gabachon.gltf
examples/IEPROES/Process1/Assets/level1/Glove_L_Long.gltf
examples/IEPROES/Process1/Assets/level1/Glove_L_Short.gltf
examples/IEPROES/Process1/Assets/level1/Glove_R_Long.gltf
examples/IEPROES/Process1/Assets/level1/Glove_R_Short.gltf
examples/IEPROES/Process1/Assets/level1/Googles_Covid.gltf
examples/IEPROES/Process1/Assets/level1/Hat.gltf
examples/IEPROES/Process1/Assets/level1/MaskN95.gltf
examples/IEPROES/Process1/Assets/level1/Mask_Covid.gltf
examples/IEPROES/Process1/vxr-teacher-template.html
examples/js/structureEntitiesProcess1.json

Added Covid level 1 assets on the scene for Process 1

Added covid assets for level 1

---

examples/IEPROES/Process1/vxr-teacher-template.html
examples/js/structureEntitiesProcess1.json

Added emissive and static mesh for level 2 and 3 on process1. Fixed name for emissive and static mesh on level 1

added emissive and static mesh for level 2 and 3 on process1

---

examples/IEPROES/Process1/Assets/level1/Hazmat_Suit.gltf
examples/IEPROES/Process1/Assets/level1/emisive/Hazmat_Suit_emisive.gltf
examples/IEPROES/Process1/Assets/level1/statics/Hazmat_Suit_static.gltf
examples/IEPROES/Process1/vxr-teacher-template.html
examples/IEPROES/Process6/Assets/Campo_Hendido_Half_Woman.gltf
examples/IEPROES/Process6/Assets/Clothed_Instruments_Vesical_Woman.gltf
examples/IEPROES/Process6/Assets/Clothed_Instruments_Vesical_Woman_Static.gltf
examples/IEPROES/Process6/vxr-teacher-template.html
examples/js/structureEntitiesProcess1.json

Updated Clothed_Instruments_Vesical and Campo_Hendido_Half on Process6. Added template and trigger for hazmatsuit on Process1

Updated assets for Process6, added hazmatsuit on Process1

---

examples/IEPROES/Process1/Assets/level1/Hazmat_Suit.gltf
examples/IEPROES/Process1/Assets/level1/statics/Escafandra_Low_static.gltf
examples/IEPROES/Process1/Assets/level1/statics/Hazmat_Suit_static.gltf
examples/IEPROES/Process1/vxr-teacher-template.html

Positions for hazmatsuit and escafandra has been modified

Updated hazmatSuit and Escafandra assets

---

examples/IEPROES/Process1/Assets/level1/emisive/Hazmat_Suit_emisive.gltf
examples/IEPROES/Process1/vxr-student-template.html
examples/IEPROES/Process1/vxr-teacher-template.html

Updated hazmat suit_emissive position

Updated teacher-template for Process 1

---

examples/IEPROES/HospitalRoomAssets/AOMap_armario.png
examples/IEPROES/HospitalRoomAssets/AOMap_mesacama.png
examples/IEPROES/HospitalRoomAssets/AOMap_silla.png
examples/IEPROES/HospitalRoomAssets/AOMap_sofa.png
examples/IEPROES/Process3/vxr-teacher-template.html
examples/IEPROES/Process5/vxr-teacher-template.html
examples/IEPROES/Process6/vxr-teacher-template.html
examples/IEPROES/Process7/vxr-teacher-template.html

Added HospitalRoom assets for Process 3 and 7

---

examples/IEPROES/Process1/vxr-teacher-template.html
examples/IEPROES/Process5/Assets/Card_Yellow5.gltf
examples/IEPROES/Process5/vxr-teacher-template.html
examples/IEPROES/Process6/Assets/Card_Yellow6.gltf
examples/IEPROES/Process6/vxr-teacher-template.html
examples/IEPROES/Process7/Assets/Card_Yellow7.gltf
examples/IEPROES/Process7/Assets/Nurse_Assistance_Card_Yellow.gltf
examples/IEPROES/Process7/vxr-teacher-template.html

Added boots for mannequin on level 1 for process 1

Updated patients cards for process 5, 6 and 7

---

examples/IEPROES/Process2/vxr-teacher-template.html
examples/IEPROES/Process3/vxr-teacher-template.html
examples/IEPROES/Process4/vxr-teacher-template.html
examples/IEPROES/Process5/vxr-teacher-template.html
examples/Models/NavMesh_05.glb
examples/Models/navMesh.glb
examples/Models/navMesh_02.glb

Added glb for nav mesh on process 02, 03, 04 and 05 and changes rotation and location for nav mesh on teacher template for the same process

Made changes on nav mesh for process 02, 03, 04 and 05

---

examples/IEPROES/NeoNato/vxr-teacher-template.html
examples/IEPROES/Process1/vxr-teacher-template.html
examples/IEPROES/Process6/vxr-teacher-template.html
examples/IEPROES/Process7/vxr-teacher-template.html
examples/Models/NavMesh_01.glb
examples/Models/NavMesh_06.glb
examples/Models/NavMesh_07.glb
examples/Models/navMesh_08.glb

Nav mesh for process 01, 06, 07 and 08, with modification on location, scale and rotation and for process 8 added the reference for gltf file

Made modification to nav mesh for process 1, 6, 7 and 8 

---

examples/IEPROES/Process1/vxr-teacher-template.html
examples/IEPROES/Process2/vxr-teacher-template.html
examples/IEPROES/Process3/vxr-teacher-template.html
examples/IEPROES/Process4/vxr-teacher-template.html
examples/IEPROES/Process5/vxr-teacher-template.html
examples/IEPROES/Process6/vxr-teacher-template.html
examples/IEPROES/Process7/vxr-teacher-template.html
examples/IEPROES/Process8/vxr-teacher-template.html
examples/Models/Infographic.gltf

On process 01, 03 and 08 need to evaluate the position for infographic

Added infographic gltf and on process 2, 4, 5, 6 and 7 verifyed the position

---

examples/IEPROES/Process2/vxr-teacher-template.html
examples/IEPROES/Process4/vxr-teacher-template.html
examples/Models/gltf/Intracath.gltf
examples/Models/gltf/Intracath_Baby.gltf

Changed rotation of the asset so the collusion is correct for both process 02 and corroborated on debug

Made changes on asset for intracath

---

examples/Models/room/Mannequin_Covid_Test.gltf
examples/Models/room/Table_005.gltf

Mannequin and table 005 have a reduced polygons and textures

Made optimization to assets used on process 01
